#!/usr/bin/env fish
# 03_ssh.fish - SSH key generation and configuration
# Idempotent: safe to run multiple times

set -l SSH_DIR ~/.ssh
set -l KEY_PATH $SSH_DIR/id_ed25519
set -l CONFIG_PATH $SSH_DIR/config

echo "=== SSH Setup ==="
echo ""

# Ensure .ssh directory exists with correct permissions
if not test -d $SSH_DIR
    mkdir -p $SSH_DIR
    echo "✓ Created $SSH_DIR"
end
chmod 700 $SSH_DIR

# Generate SSH key if not present
if not test -f $KEY_PATH
    echo "No SSH key found. Generating new Ed25519 key..."
    echo ""
    read -P "Email/comment for SSH key (e.g., you@example.com): " ssh_email

    if test -z "$ssh_email"
        echo "ERROR: Email required for SSH key."
        exit 1
    end

    ssh-keygen -t ed25519 -C $ssh_email -f $KEY_PATH
    echo ""
    echo "✓ SSH key generated"
else
    echo "· SSH key already exists at $KEY_PATH"
end

# Set correct permissions
chmod 600 $KEY_PATH
test -f $KEY_PATH.pub; and chmod 644 $KEY_PATH.pub

# Create SSH config if missing
if not test -f $CONFIG_PATH
    echo ""
    echo "Creating SSH config..."
    echo "# SSH Config - generated by mac-bootstrap
# Add your hosts below

Host *
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519
  ServerAliveInterval 60
  ServerAliveCountMax 5

# Example GitHub config:
# Host github.com
#   HostName github.com
#   User git
#   IdentityFile ~/.ssh/id_ed25519
" > $CONFIG_PATH
    chmod 600 $CONFIG_PATH
    echo "✓ Created $CONFIG_PATH"
else
    echo "· SSH config already exists"
end

# Add key to SSH agent
echo ""
echo "Adding key to SSH agent..."
ssh-add --apple-use-keychain $KEY_PATH 2>/dev/null
or ssh-add $KEY_PATH 2>/dev/null
or echo "· Key may already be loaded or agent not running"

# Display public key
echo ""
echo "=== Your Public Key ==="
echo ""
cat $KEY_PATH.pub
echo ""
echo "---"
echo "Tip: pbcopy < ~/.ssh/id_ed25519.pub  # copy to clipboard"
echo "Add this key to GitHub: https://github.com/settings/keys"
